In [ ]:
# PyCaretとは
# 公式ページ https://pycaret.org/

# 1,短いコードで機械学習ができる
# 2,自動化 (AutoML)
# 3,オープンソース
# 4,scikit-learnや他の機械学習パッケージのwrapper

# Agenda
# 1,回帰
# 2,分類
# 3,クラスタリング

# 他にも，異常検出(anomaly detection)，
# 自然言語処理(natural language processing: NLP)，
# アソシエーション・ルール・マイニングが含まれている．

In [4]:
!pip install pycaret #すべてのパッケージをインストールするなら !pip install pycaret[full]
from pycaret.utils import enable_colab
enable_colab()

Collecting pycaret
  Downloading pycaret-2.3.6-py3-none-any.whl (301 kB)
     |████████████████████████████████| 301 kB 5.0 MB/s
Requirement already satisfied: plotly>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from pycaret) (4.4.1)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.5.0)
Collecting mlxtend>=0.17.0
  Downloading mlxtend-0.19.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 60.6 MB/s
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.2.2)
Requirement already satisfied: seaborn in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.11.2)
Requirement already satisfied: spacy<2.4.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (2.2.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.1.5)
Requirement already satisfied: yellowbrick>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.3.post1)
Requirement already satisfied: IPython in /usr/local/lib/python3.7/dist-packages (from pycaret) (5.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.1.0)
Collecting pandas-profiling>=2.8.0
  Downloading pandas_profiling-3.1.0-py2.py3-none-any.whl (261 kB)
     |████████████████████████████████| 261 kB 59.6 MB/s
Collecting Boruta
  Downloading Boruta-0.3-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 4.6 MB/s
Collecting scikit-plot
  Downloading scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Collecting umap-learn
  Downloading umap-learn-0.5.2.tar.gz (86 kB)
     |████████████████████████████████| 86 kB 5.8 MB/s
Requirement already satisfied: cufflinks>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.17.3)
Collecting imbalanced-learn==0.7.0
  Downloading imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
     |████████████████████████████████| 167 kB 58.7 MB/s
Collecting pyod
  Downloading pyod-0.9.7.tar.gz (114 kB)
     |████████████████████████████████| 114 kB 70.8 MB/s
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.7/dist-packages (from pycaret) (7.6.5)
Requirement already satisfied: scipy<=1.5.4 in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.4.1)
Collecting kmodes>=0.10.1
  Downloading kmodes-0.11.1-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.2.5)
Collecting mlflow
  Downloading mlflow-1.23.0-py3-none-any.whl (15.6 MB)
     |████████████████████████████████| 15.6 MB 51.5 MB/s
Requirement already satisfied: pyyaml<6.0.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.13)
Requirement already satisfied: textblob in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.15.3)
Collecting scikit-learn==0.23.2
  Downloading scikit_learn-0.23.2-cp37-cp37m-manylinux1_x86_64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 45.7 MB/s
Collecting pyLDAvis
  Downloading pyLDAvis-3.3.1.tar.gz (1.7 MB)
     |████████████████████████████████| 1.7 MB 61.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: gensim<4.0.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.6.0)
Collecting lightgbm>=2.3.1
  Downloading lightgbm-3.3.2-py3-none-manylinux1_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 53.9 MB/s
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn==0.7.0->pycaret) (1.19.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.23.2->pycaret) (3.0.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from cufflinks>=0.17.0->pycaret) (1.15.0)
Requirement already satisfied: colorlover>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from cufflinks>=0.17.0->pycaret) (0.3.0)
Requirement already satisfied: setuptools>=34.4.1 in /usr/local/lib/python3.7/dist-packages (from cufflinks>=0.17.0->pycaret) (57.4.0)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from gensim<4.0.0->pycaret) (5.2.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (4.4.2)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (2.6.1)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (5.1.1)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (0.8.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (1.0.18)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (4.8.0)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (5.1.3)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (0.2.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (1.0.2)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (4.10.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (3.5.2)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (5.3.5)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (5.1.1)
Requirement already satisfied: wheel in /usr/local/lib/python3.7/dist-packages (from lightgbm>=2.3.1->pycaret) (0.37.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (3.0.6)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (4.9.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (4.3.3)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (4.10.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (21.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (0.18.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (3.10.0.2)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (5.4.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (3.7.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas->pycaret) (2018.9)
Collecting requests>=2.24.0
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.6 MB/s
Requirement already satisfied: markupsafe~=2.0.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (2.0.1)
Collecting htmlmin>=0.1.12
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
Collecting tangled-up-in-unicode==0.1.0
  Downloading tangled_up_in_unicode-0.1.0-py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 37.6 MB/s
Requirement already satisfied: missingno>=0.4.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (0.5.0)
Collecting phik>=0.11.1
  Downloading phik-0.12.0-cp37-cp37m-manylinux2010_x86_64.whl (675 kB)
     |████████████████████████████████| 675 kB 56.2 MB/s
Collecting visions[type_image_path]==0.7.4
  Downloading visions-0.7.4-py3-none-any.whl (102 kB)
     |████████████████████████████████| 102 kB 12.0 MB/s
Collecting pydantic>=1.8.1
  Downloading pydantic-1.9.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.9 MB)
     |████████████████████████████████| 10.9 MB 44.4 MB/s
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (2.11.3)
Requirement already satisfied: tqdm>=4.48.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (4.62.3)
Collecting pyyaml<6.0.0
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
     |████████████████████████████████| 636 kB 63.3 MB/s
Collecting multimethod>=1.4
  Downloading multimethod-1.6-py3-none-any.whl (9.4 kB)
Collecting joblib
  Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
     |████████████████████████████████| 303 kB 62.2 MB/s
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (2.6.3)
Collecting imagehash
  Downloading ImageHash-4.2.1.tar.gz (812 kB)
     |████████████████████████████████| 812 kB 47.9 MB/s
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (7.1.2)
Collecting scipy<=1.5.4
  Downloading scipy-1.5.4-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 1.5 MB/s
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly>=4.4.1->pycaret) (1.3.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->IPython->pycaret) (0.2.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.0.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2021.10.8)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.1.3)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (0.4.1)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (3.0.6)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.0.6)
Requirement already satisfied: thinc==7.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (7.4.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (2.0.6)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.0.5)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (0.9.0)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.0.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets->pycaret) (5.3.1)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (5.6.1)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.12.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.8.0)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets->pycaret) (22.3.0)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.7/dist-packages (from terminado>=0.8.1->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.7.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.7/dist-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (1.2.0)
Requirement already satisfied: sqlparse>=0.3.1 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (0.4.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.4.29)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.3.0)
Collecting databricks-cli>=0.8.7
  Downloading databricks-cli-0.16.2.tar.gz (58 kB)
     |████████████████████████████████| 58 kB 5.7 MB/s
Collecting gunicorn
  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 7.4 MB/s
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (7.1.2)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (0.3)
Collecting querystring-parser
  Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
Requirement already satisfied: Flask in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.1.4)
Collecting prometheus-flask-exporter
  Downloading prometheus_flask_exporter-0.18.7-py3-none-any.whl (17 kB)
Requirement already satisfied: protobuf>=3.7.0 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (3.17.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (21.3)
Collecting docker>=4.0.0
  Downloading docker-5.0.3-py2.py3-none-any.whl (146 kB)
     |████████████████████████████████| 146 kB 63.6 MB/s
Collecting alembic
  Downloading alembic-1.7.5-py3-none-any.whl (209 kB)
     |████████████████████████████████| 209 kB 66.5 MB/s
Collecting gitpython>=2.1.0
  Downloading GitPython-3.1.26-py3-none-any.whl (180 kB)
     |████████████████████████████████| 180 kB 57.1 MB/s
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.7/dist-packages (from databricks-cli>=0.8.7->mlflow->pycaret) (0.8.9)
Collecting websocket-client>=0.32.0
  Downloading websocket_client-1.2.3-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 1.9 MB/s
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.9-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.7 MB/s
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting Mako
  Downloading Mako-1.1.6-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 4.5 MB/s
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->mlflow->pycaret) (1.1.2)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask->mlflow->pycaret) (1.0.1)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask->mlflow->pycaret) (1.1.0)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.7.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.8.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (4.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.7/dist-packages (from prometheus-flask-exporter->mlflow->pycaret) (0.12.0)
Collecting pandas
  Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     |████████████████████████████████| 11.3 MB 46.1 MB/s
Collecting pyLDAvis
  Downloading pyLDAvis-3.3.0.tar.gz (1.7 MB)
     |████████████████████████████████| 1.7 MB 44.1 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
  Downloading pyLDAvis-3.2.2.tar.gz (1.7 MB)
     |████████████████████████████████| 1.7 MB 60.8 MB/s
Requirement already satisfied: numexpr in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (2.8.1)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (0.16.0)
Collecting funcy
  Downloading funcy-1.17-py2.py3-none-any.whl (33 kB)
Requirement already satisfied: numba>=0.35 in /usr/local/lib/python3.7/dist-packages (from pyod->pycaret) (0.51.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.7/dist-packages (from pyod->pycaret) (0.10.2)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.7/dist-packages (from numba>=0.35->pyod->pycaret) (0.34.0)
Requirement already satisfied: patsy>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from statsmodels->pyod->pycaret) (0.5.2)
Collecting pynndescent>=0.5
  Downloading pynndescent-0.5.6.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 75.6 MB/s
Building wheels for collected packages: htmlmin, imagehash, databricks-cli, pyLDAvis, pyod, umap-learn, pynndescent
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=fc70466d1fa8c35240156556f7503b2ba3e80151ee76568e521762eb504d3659
  Stored in directory: /root/.cache/pip/wheels/70/e1/52/5b14d250ba868768823940c3229e9950d201a26d0bd3ee8655
  Building wheel for imagehash (setup.py) ... done

#回帰

In [1]:
# 広告による売り上げの予測
# 広告のデータ http://logopt.com/data/Advertising.csv を用いる．
# テレビ(TV)，ラジオ(Radio)，新聞(Newspaper)への広告から売り上げ(Sales)を予測する．

import pandas as pd #まずはpandasモジュールを準備する．
df = pd.read_csv('http://logopt.com/data/Advertising.csv', index_col =0) #0行目をインデックスにする．
df.tail()

# 独立変数（特徴ベクトル）XX は TV, Radio, Newspaperの列，従属変数（ターゲット） yy は Salesの列

        TV  Radio  Newspaper  Sales
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

#PyCaretの基本手順

In [5]:
# 手順１： setup(データフレーム）で準備をする． 引数 target でターゲットの列を指定． 引数 session_id で乱数の種を指定．

# 手順２： compare_modelsでモデルの比較を行う． 引数 fold で交差検証用のデータの分割数を指定． 
# 返値は最良の評価値のモデルインスタンス． （もしくはcreate_modelでモデルを生成する．）

# 注意： 遅い計算機で実行する際には，計算時間がかかるモデルを除いておくと良い．
# 引数excludeで除きたいモデルのリストを入れる． たとえば， compare_models(exclude = ['catboost']) とするとCatBoostを除いてモデルの比較を行ってくれる．

# 手順３： predict_modelで予測を行う．

from pycaret.regression import *   #回帰関連の関数のインポート
reg = setup(df, target = 'Sales', session_id=123)

IntProgress(value=0, description='Processing: ', max=3)

Initiated  . . . . . . . . . . . . . . . . . .            14:10:11
Status     . . . . . . . . . . . . . . . . . .  Preprocessing Data

Text(value="Following data types have been inferred automatically, if they are correct press enter to continue…

          Data Type
TV          Numeric
Radio       Numeric
Newspaper   Numeric
Sales         Label

KeyboardInterrupt: ignored

In [ ]:
best_model = compare_models(fold=5)
best_model

In [ ]:
best_model_results = pull() #結果をデータフレームとして得る．
best_model_results.to_csv("best_model.csv")

In [ ]:
# 回帰モデル
# No.	略称	回帰モデル	概要
# 1	et	Extra Trees Regressor	ランダムに分割してアンサンブルする決定木ベースの手法
# 2	gbr	Gradient Boosting Regressor	勾配ブースティング法
# 3	xgboost	Extreme Gradient Boosting	xgブースト （勾配ブースティング法に正則化を追加）
# 4	rf	Random Forest Regressor	ランダム森（ブートストラップによるランダムサンプリングと決定木のアンサンブル）
# 5	catboost	CatBoost Regressor	カテゴリー変数の扱いに工夫を入れた勾配ブースティング法
# 6	ada	AdaBoost Regressor	適応型の勾配ブースティング法
# 7	dt	Decision Tree Regressor	決定木
# 8	lightgbm	Light Gradient Boosting Machine	勾配ブースティング法の軽量版
# 9	knn	K Neighbors Regressor	kk-近傍法
# 10	lasso	Lasso Regression	Lasso回帰（正則化を入れた線形回帰）
# 11	en	Elastic Net	Elastic Net（正則化を入れた線形回帰）
# 12	lar	Least Angle Regression	予測値と教師データの偏差と相関が大きい特徴量を1つずつ追加していく方法
# 13	lr	Linear Regression	線形回帰
# 14	ridge	Ridge Regression	リッジ回帰（正則化を入れた線形回帰）
# 15	br	Bayesian Ridge	ベイズリッジ回帰
# 16	huber	Huber Regressor	Huber回帰
# 17	omp	Orthogonal Matching Pursuit	貪欲に特徴量を1つずつ追加していく方法
# 18	llar	Lasso Least Angle Regression	LassoにLeast Angle Regressionを適用して特徴量選択
# 19	par	Passive Aggressive Regressor	オンライン型の学習

## 予測

In [ ]:
predict_model(best_model)

#可視化の基本手順(回帰)

In [ ]:
# 可視化（回帰）
# 手順１： plot_model(モデルインスタンス)で描画する．引数plotで描画の種類を指定する．既定値は残差プロット．
# 手順２：interpret_model（モデルインスタンス）で，結果の解釈を可視化する．

# plot_modelの引数plotの種類

# ‘residuals’: 残差プロット（既定値）
# ‘error’ : 誤差プロット
# ‘cooks’: Cookの距離プロット（外れ値をみる）
# ‘feature': 特徴重要度プロットp
# ‘learning’: 学習曲線
# ‘vc’: 検証曲線
# ‘manifold’: 次元削減を行い特徴を2次元に射影した図
# ‘parameter’: モデルのパラメータを表で表示
# ‘tree’: 決定木の図示（木ベースの場合のみ）

plot_model(best_model)

In [ ]:
plot_model(best_model, plot = 'error')

In [ ]:
plot_model(best_model, plot = 'cooks')

In [ ]:
plot_model(best_model, plot = 'feature')

In [ ]:
plot_model(best_model, plot = 'learning')

In [ ]:
plot_model(best_model, plot = 'vc')

In [ ]:
plot_model(best_model, plot = 'manifold')

In [ ]:
plot_model(best_model, plot = 'parameter')

In [ ]:
# 小さな（深さ3の）決定木 (dt) のモデルを作って可視化する．

dt = create_model('dt', max_depth=3)
plot_model(dt, plot = 'tree')

#モデルの解釈

In [ ]:
# interpret_model関数は，SHAP値 (Shapley value)を計算する．

# interpret_modelの引数plotの種類

# 1,‘summary’: 各特徴のSHAP値がターゲットに与える影響を表した図 （既定値）
# 2,‘correlation’: 特徴とSHAP値の相関図
# 3,‘reason’: 個々のデータに対するSHAP値

interpret_model(best_model)

In [ ]:
interpret_model(best_model, plot = 'correlation')

In [ ]:
interpret_model(best_model, plot = 'reason', observation = 10)

In [ ]:
# 問題 (SAT,GPA)
# http://logopt.com/data/SATGPA.csv データを用いて，2種類のSATの成績からGPAを予測せよ．
# データをそのまま使うと'MathSAT'列と'VerbalSAT'列をカテゴリー変数としてしまうので，浮動小数点数に変換しておく．

gpa = pd.read_csv("http://logopt.com/data/SATGPA.csv", index_col=0, dtype={'MathSAT':float, 'VerbalSAT':float})
gpa.head()

In [ ]:
# 問題（住宅価格）
# http://logopt.com/data/Boston.csv のBostonの住宅データを用いて回帰分析を行え．

# medvが住宅の価格で，他のデータ（犯罪率や人口など）から予測する．

In [ ]:
# 問題（車の燃費）
# http://logopt.com/data/Auto.csv の車の燃費のデータを用いて回帰分析を行え．

# データの詳細については，

# https://vincentarelbundock.github.io/Rdatasets/doc/ISLR/Auto.html

# を参照せよ．

# 最初の列が燃費（mpg: Mile Per Gallon)であり，これを他の列の情報を用いて予測する．最後の列は車名なので無視して良い．

In [ ]:
# 問題（コンクリートの強度）
# 以下のコンクリートの強度の例題に対して，strength列の強度を他の列の情報から，線形回帰を用いて推定せよ．

concrete = pd.read_csv("http://logopt.com/data/concrete.csv")
concrete.head()

In [ ]:
# 問題（シェアバイク）
# 以下のシェアバイクのデータに対して，riders列が利用者数を，線形回帰を用いて推定せよ．ただし，date列とcasual列は除いてから回帰を行え．
# また，なぜcasual列を含めて推定をしないのか考察せよ．

bikeshare = pd.read_csv("http://logopt.com/data/bikeshare.csv")
bikeshare.head()

In [ ]:
# ダイヤモンドの価格の予測（カテゴリー変数）
# http://logopt.com/data/Diamond.csv からダイアモンドの価格データを読み込み，回帰による予測を行う．
# 列は ["carat","colour","clarity","certification","price"] であり，他の情報から価格(price)の予測を行え．
# カラット(carat)以外の列は情報が文字列として保管されている．
# これはカテゴリー変数とよばれる．
# PyCaretでは，前処理関数setupで，自動的に変換してくれるので，手順は前とまったく同じである．

import pandas as pd
diamond = pd.read_csv('http://logopt.com/data/Diamond.csv', index_col=0)
diamond.head()

In [ ]:
reg = setup(diamond, target = 'price', session_id=123)

In [ ]:
best_model = compare_models(fold=5)

In [ ]:
plot_model(best_model, plot="feature")

In [ ]:
# 問題（車の価格）
# http://logopt.com/data/carprice.csv から車の価格データを読み込み，回帰による予測を行え．

# データの詳細は https://vincentarelbundock.github.io/Rdatasets/doc/DAAG/carprice.html にある．

# 車種(Type)，100マイル走る際のガロン数（gpm100），都市部での1ガロンあたりの走行距離（MPGcity），高速道路での１ガロン当たりの走行距離（MPGhighway）から，価格(Price)を予測せよ．

In [ ]:
# 問題（チップ）
# 以下のtipsデータに対して回帰を用いてもらえるチップの額(tip)を予測せよ．

import seaborn as sns
tips = sns.load_dataset('tips')
tips.head()

#分類

In [ ]:
# スパムの判定
# メールがスパム（spam；迷惑メイル）か否かを判定する例題を用いる．
# https://archive.ics.uci.edu/ml/datasets/spambase

# 様々な数値情報から，is_spam列が 11 （スパムでない）か， 00 （スパム）かを判定する．

import pandas as pd
spam = pd.read_csv("http://logopt.com/data/spam.csv")
spam.head()

In [ ]:
# is_spam列が従属変数（ターゲット）yy になり，それ以外の列が独立変数（特徴ベクトル）XX になる

from pycaret.classification import *
clf = setup(data = spam, target = 'is_spam', session_id=123)

In [ ]:
best_model = compare_models(exclude=["catboost"])

In [ ]:
# 分類モデル
# No.	略称	分類モデル	概要
# 1	et	Extra Trees Classifier	ランダムに分割してアンサンブルする決定木ベースの手法
# 2	gbc	Gradient Boosting Classifier	勾配ブースティング法
# 3	xgboost	Extreme Gradient Boosting	xgブースト （勾配ブースティング法に正則化を追加）
# 4	rf	Random Forest Classifier	ランダム森（ブートストラップによるランダムサンプリングと決定木のアンサンブル）
# 5	catboost	CatBoost Classifier	カテゴリー変数の扱いに工夫を入れた勾配ブースティング法
# 6	ada	AdaBoost Classifier	適応型の勾配ブースティング法
# 7	dt	Decision Tree Classifier	決定木
# 8	lightgbm	Light Gradient Boosting Machine	勾配ブースティング法の軽量版
# 9	knn	K Neighbors Classifier	kk-近傍法
# 10	lda	Linear Discriminant Analysis	線形判別分析（すべてのクラスで同じ正規分布を仮定）
# 11	qda	Quadratic Discriminant Analysis	2次判別分析（各クラスで異なる正規分布を仮定）
# 12	lr	Logistic Regression	ロジスティック回帰
# 13	ridge	Ridge Classifier	　リッジ分類
# 14	nb	Naive Bayes	単純ベイズ
# 15	svm	SVM - Linear Kernel	サポートベクトルマシン（線形カーネル）

#可視化の基本手順(分類)

In [ ]:
# plot_model(モデルインスタンス)で描画する．引数plotで描画の種類を指定する． interpret_modelは回帰と同じ．
# plot_model関数の引数plotの種類（回帰と同じものは省略）

# ‘auc’: ROC曲線の下の面積 （既定値）
# ‘threshold’: 識別閾値（discrimination threshold）を変えたときの評価尺度の変化
# ‘pr’ : 適合率（precision）と再現率（recall）を表示
# ‘confusion_matrix’: 混合行列
# ‘error’: クラスごとの誤差を表示
# ‘class_report’: クラスごとの評価尺度のヒートマップ
# ‘boundary’: 決定の境界の図示
# ‘calibration’: キャリブレーション（検量）曲線の図示
# ‘dimension’ - Dimension Learning
# ‘gain’ - データの一部（パーセンテージ）でどれだけクラスを予測できたか(これをgainと呼ぶ）を表した図
# ‘lift’ - 上のgainとベースライン（予測モデルを使わない場合）の比をプロットしたもの

In [ ]:
# ROC曲線
# ROC: 受信者操作特性（receiver operating characteristic)

# https://ja.wikipedia.org/wiki/受信者操作特性

# 閾値を1から0に変えると，recall (true positive rate) が増加し，precision (1-false positive rate) が減少する．

# x軸に false positive rate，y軸にtrue positive rateをとると，両方とも1に近づく曲線になる．

# 曲線の下の面積 (AUC: area under the curve) が評価尺度（大きいほど良い）になる．

# true positive rate = recall = TP/(TP+FN)
# false positive rate = 1-precision = FP/(TN+FP)

plot_model(best_model, plot = 'auc')

In [ ]:
plot_model(best_model, plot = 'threshold')

In [ ]:
plot_model(best_model, plot = 'pr')

In [ ]:
# 混合行列
# 1,positive : 予測(prediction)が １（スパムでない）；(注意）positiveか否かは相対的なものであるので，どちらでも良い．0（スパム）をpositiveとすることも可能．
# 2,negative : 予測が1（スパム）
# 3,true : あたり
# 4,false : はずれ

plot_model(best_model, plot = 'confusion_matrix')

In [ ]:
plot_model(best_model, plot='error')

In [ ]:
plot_model(best_model, plot='class_report')

In [ ]:
plot_model(best_model, plot='boundary')

In [ ]:
plot_model(best_model, plot='calibration')

In [ ]:
plot_model(best_model, plot='dimension')

In [ ]:
plot_model(best_model, plot='lift')

In [ ]:
plot_model(best_model, plot='gain')

#iris（アヤメ）のデータ

In [ ]:
# 2値分類だけでなく，3種類以上のものの分類もできる．
# 以下ではアヤメのデータを用いて分類を行い，3種類のアヤメを分類する．

import plotly.express as px
iris = px.data.iris()
iris.head()

In [ ]:
clf = setup(data = iris, target = 'species', ignore_features=["species_id"], session_id=123)

In [ ]:
best_model = compare_models()

#可視化

In [ ]:
# 以下の2つの可視化を追加
# 1,どの特徴が重要かを可視化するRadViz
# 2,重要と思われる2つの特徴に対して，ロジスティック回帰の分類がどのように行われたかを示すDecisionViz（決定の境界を示す）

# スパムと同じ可視化
# 1,混合行列 (ConfusionMatrix)
# 2,分類レポート (ClassificationReport)
# 3,ROC曲線 (ROCAUC)

# 3値以上の場合には，閾値を変化させる可視化はできないことに注意

plot_model(best_model, plot = 'confusion_matrix')

In [ ]:
plot_model(best_model, plot='boundary')

In [ ]:
plot_model(best_model, plot='feature')

In [ ]:
# 毒キノコの判定
# ここでは，データから毒キノコか否かを判定する.
# target列がターゲット（従属変数）であり，edibleが食用，poisonousが毒である．
# 他の列のデータもすべて数値ではない．
# PyCaretでは，自動的に前処理をしてくれるので，手順はまったく同じである．

mashroom = pd.read_csv("http://logopt.com/data/mashroom.csv")
mashroom.head()

In [ ]:
# 前処理
# setupで前処理を行うとき，引数log_experimentをTrueにしておくと，実験結果を保存してくれる． また，引数 experiment_name で実験名を指定し， 引数 log_plots をTrueにすることによって，図を保存する．

from pycaret.classification import *
clf = setup(data = mashroom, target = 'target', session_id=123, log_experiment = True, experiment_name = 'mashroom_1', log_plots=True)

In [ ]:
# ベスト５の手法を保存
best_5 = compare_models(exclude=["catboost"], n_select = 5)

In [ ]:
# チューニング
# ベスト5の方法のパラメータをチューニングする．

tuned = [tune_model(i) for i in best_5]

In [ ]:
# Bagging
# Bagging (Bootstrap aggregating) はアンサンブル法の一種である． 繰り返しを許してサンプリング(bootstrap) し， 結果の多数決 (aggregating)をとることによって，元の手法の分散を減らし，過剰適合を減らす．

bagged = [ensemble_model(i) for i in tuned]

In [ ]:
# Blending
# 異なる手法の多数決をとる方法がblendingである．

blender = blend_models(estimator_list = tuned)

In [ ]:
# 実験結果を表示
!mlflow ui

In [ ]:
# 問題（クレジットカード）
# 以下のクレジットカードのデフォルトの判定データに対して分類を行え．

# default列にデフォルトか否かの情報があり，他の列の情報を用いて分類せよ．

# ただし，データ数が多いので，引数に exclude=["catboost"] を入れて CatBoostを除いてモデルを比較せよ．

credit = pd.read_csv("http://logopt.com/data/credit.csv")
credit.tail()

In [ ]:
# 問題（部屋）
# 以下の部屋が使われているか否かを判定するデータに対して分類を行え．

# occupancy列が部屋が使われているか否かを表す情報であり，これをdatetime列以外の情報から分類せよ．

occupancy = pd.read_csv("http://logopt.com/data/occupancy.csv")
occupancy.tail()

In [ ]:
# 問題（タイタニック）
# titanicデータに対して分類を行い，死亡確率の推定を行え．

# ただし， モデルの比較の際には， fold=5, exclude=["ridge"] を引数で与えよ．

titanic = pd.read_csv("http://logopt.com/data/titanic.csv")
titanic.head()

In [ ]:
# 問題（胸部癌）
# http://logopt.com/data/cancer.csv にある胸部癌か否かを判定するデータセットを用いて分類を行え．

# 最初の列diagnosisが癌か否かを表すものであり，'M'が悪性（malignant），'B'が良性（benign）を表す．

cancer = pd.read_csv("http://logopt.com/data/cancer.csv", index_col=0)
cancer.head()

#クラスタリング

In [ ]:
# UCI機械学習レポジトリのワインに関するデータセットを用いてクラスタリングを解説する．
# 使用するのは kk-平均法である．
# 元データはこちらに格納されている．

# http://logopt.com/data/wine.data
# 列名は https://archive.ics.uci.edu/ml/datasets/Wine で解説されている．

import pandas as pd
L = [ 'Alcohol', 'Malic','Ash', 'Alcalinity', 'Magnesium', 'Phenols', 'Flavanoids', 'Nonflavanoid',
     'Proanthocyanins', 'Color', 'Hue', 'OD280', 'OD315', 'Proline']
wine = pd.read_csv('http://logopt.com/data/wine.data',names=L)
wine.head()

In [ ]:
from pycaret.clustering import *
cluster = setup(wine)

In [ ]:
# クラスタリングもcreate_model関数で生成する．引数modelでモデルの種類を設定する．

# 引数modelの種類 （すべてscikit-learnを利用している）：

# ‘kmeans’: kk-平均法（各点の重心までの距離の和を最小化）
# ‘ap’: Affinity Propagation
# ‘meanshift’: Mean shift Clustering
# ‘sc’: スペクトラル・クラスタリング（低次元に射影してからkk-平均法）
# ‘hclust’: 階層的クラスタリング法
# ‘dbscan’: DBSCAN (Density-Based Spatial Clustering)
# ‘optics’: DBSCANの一般化
# ‘birch’ : Birch Clustering
# ‘kmodes’: kk-Modes Clustering

# クラスターの数は，引数num_clusters（既定値は4）で与える．

kmeans = create_model('kmeans', num_clusters=4)

In [ ]:
# 得られたクラスタリングを元のデータフレームに書き込む．

kmean_results = assign_model(kmeans)
kmean_results.head()

In [ ]:
# クラスタリングの評価尺度
# Silhouette: シルエット値； クラスター内の平均距離aと最も近い別のクラスターとの平均距離bに対して (b - a) / max(a, b)と定義される． 他のクラスターと離れているとき1に近くなる．
# Calinski-Harabasz: クラスター間の分散とクラスター内の分散の比を合計したもの；大きいほどクラスターが分離している．
# Davies-Bouldin：クラスター内と最も類似しているクラスター間の類似度の比の平均；小さいほどクラスターが分離している．
# Homogeneity: 均質性尺度；正解が必要；0から1の値ととり，1に近いほど良い．
# Rand Index： 2つのクラスターに対して，正解と同じ割当になっている割合を表す尺度；-1から1の値をとり，1のとき正解と同じ．
# Completeness： 正解のクラスターに含まれるデータが，同じクラスターに含まれる割合；0から1の値をとり，1に近いほど良い．

ap = create_model('ap')

In [ ]:
meanshift = create_model('meanshift')

In [ ]:
sc = create_model('sc')

In [ ]:
hclust = create_model('hclust')

In [ ]:
dbscan = create_model('dbscan') #Bug?

In [ ]:
optics = create_model('optics')

In [ ]:
birch = create_model('birch')

In [ ]:
kmodes = create_model('kmodes')

#可視化（クラスタリング）

In [ ]:
# plot_model（モデルインスタンス）で可視化する．

# Plotlyの図は Jupyterlabでは表示されない． save引数で保存してから， Jupyterlabの拡張機能 jupyterlab-chart-editor をインストールし，別ウィンドウで生成されたhtmlファイルを開く（Trust HTMLを押す）．

# plot_model関数の引数plotの種類

# ‘cluster’: クラスターを主成分分析 (PCA) によって2次元に表示した図 (Plotly)
# ‘tsne’: クラスターをt-SNE(t-Distributed Stochastic Neighbor Embedding)によって３次元に表示した図(Plotly)
# ‘elbow’: 分割数を表すパラメータ kk の適正化 （エルボー法）の図
# ‘silhouette’ - シルエット係数 (クラスター内の平均距離aと最も近い別のクラスターとの平均距離bに対して (b - a) / max(a, b)と定義される；他のクラスターと離れているとき1に近くなる）の図示
# ‘distance’: クラスター間の距離の図示
# ‘distribution’ -クラスターに含まれるデータ数の分布図(Plotly)

plot_model(kmeans, save=True)

In [ ]:
plot_model(kmeans, plot="tsne", save=True)

In [ ]:
plot_model(kmeans, plot = 'elbow')

In [ ]:
plot_model(kmeans, plot = 'silhouette')

In [ ]:
plot_model(kmeans, plot = 'distance')

In [ ]:
plot_model(kmeans, plot = 'distribution', save=True)

In [ ]:
# 問題（アヤメ）
# irisのデータセットの各データを kk-平均法を用いて3つのクラスターに分けて可視化せよ． また，他の手法を1つ選んでクラスタリングと可視化をし， kk-平均法と比較せよ．

iris = px.data.iris()
iris.head()